### ISSUE TITLE
Custom button pic

### ISSUE THREAD

**Issue by fly74** [Chargnn/Octoprint-CmdExec#2]
Thank you so much, I was looking for something to switch my LED stripes from octoprint.

**Comment by fly74** [comment]
Can you make the button pic customizable and use a uploaded pic?

**Comment by alexis-coulombe** [comment]
Sure! I'll work on it later this week :)

**Comment by fly74** [comment]
Whats the actual dimension and type of the pic?

**Comment by alexis-coulombe** [comment]
> Whats the actual dimension and type of the pic?

The icons are taken from fontawesome directly, i've added a list of icons to choose in the plugin's setting page. 
Update should be available soon in octoprint!

I will need to update the plugin description, here's the list for now: 
![image](https://github.com/Chargnn/Octoprint-CmdExec/assets/22302902/f12a28d6-982a-4adb-8a8c-d9d340dfece4)

PS: 
release 1.0.4
https://github.com/Chargnn/Octoprint-CmdExec/commit/b187602141f5a28013fbff4e13e865f6209498b0

**Comment by fly74** [comment]
That would be perfect.

**Comment by fly74** [comment]
Works great, but there should be an hint, the Octoprint has to be restartet to take affect of the changed pic. Or force a restart when changed like the install of a plugins is asking for.
