### ISSUE TITLE
Hint for changed pic

### ISSUE THREAD

**Issue by fly74** [Chargnn/Octoprint-CmdExec#3]
Pic selection is great, but there should be an hint, that Octoprint has to be restarted to take affect of the change. Or force a restart when changed like the install of a plugins is asking for.

**Comment by alexis-coulombe** [comment]
From my testing, you only need to reload the page to see the new icon. But i'll add a hint 👍

**Comment by alexis-coulombe** [comment]
Will be released on next plugin update!
