### ISSUE TITLE
Icon text information

### ISSUE THREAD

**Issue by sp7dpt** [Chargnn/Octoprint-CmdExec#4]
Can you add icon text information on mouse over by user input?

![image](https://github.com/alexis-coulombe/Octoprint-CmdExec/assets/54576080/2f375c7b-00da-4c31-8e76-c6e2bb707a79)

I changed your code for my needs.

**Comment by alexis-coulombe** [comment]
Good idea, will work on that for next release. Thanks !

**Comment by alexis-coulombe** [comment]
Release published, a plugin update will be available soon

I also see that you probably need another icon (the open door), i added it and some more to the settings page.

**Comment by alexis-coulombe** [comment]
Version 1.0.6 is up on the plugin page https://plugins.octoprint.org/plugins/cmdexec/
