### ISSUE TITLE
Update automatically

### ISSUE THREAD

**Issue by fly74** [Chargnn/Octoprint-CmdExec#5]
Hi Devs, why is the update not offered by the pluginmanager? Because I installed via URL?

**Comment by fly74** [comment]
Via pluginmanager only 1.0.4 is offered.

**Comment by alexis-coulombe** [comment]
Sorry i can't manage how and when the plugin is updated in the plugin manager for octoprint. More info on the octoprint docs: https://docs.octoprint.org/en/master/plugins/distributing.html

> After you published the new release, you can verify it on your installed octoprint, with force checking the updates under the advanced options (in the software updates menu in the settings). **The new versions will appear to the plugin users in the next 24 hours (it depends on their cache refreshes).**
