### ISSUE TITLE
Running python file

### ISSUE THREAD

**Issue by Adam-yes** [Chargnn/Octoprint-CmdExec#6]
Hey Alexis,

First of all - Thank you for that! I really like your cmdExec plugin! Here's my situation: I want to plug in a USB device into my Raspberry Pi and execute a Python script on the Pi while OctoPrint is running. I need to send the results of the Python script via MQTT (not using the MQTT plugin). Is it possible to save the script on the Pi and execute it there? Do you have any tips on how to save and execute the script on the Pi?

I appreciate your help and effort!

Cheers!

**Comment by alexis-coulombe** [comment]
I don't have much knowledge of MQTT, but i can still help.

How does your python script output the result ? Directly in the console or in a file ?

Create a bash script on the Pi, you then can read the result of your script with 
```
results=$(cat "result.txt")
```

You could then publish the result with mosquitto_pub using 
```
mosquitto_pub -h "$MQTT_BROKER" -p "$MQTT_PORT" -u "$MQTT_USER" -P "$MQTT_PASS" -t "$MQTT_TOPIC" -m "$results"
```

And execute the bash script using my plugin directly. Does it make sense for you ?
Here's an exemple of your bash script: 
```
sudo apt-get install mosquitto-clients
```
```
#!/bin/bash

# Change the following variables to match your setup
MQTT_BROKER="mqtt_broker_ip"
MQTT_PORT="mqtt_broker_port"
MQTT_TOPIC="mqtt_topic"
MQTT_USER="mqtt_username"
MQTT_PASS="mqtt_password"

# Execute the Python script (replace script.py with your actual Python script name)
python3 "script.py"

# Read the results (replace result.txt with the file generated by your Python script)
results=$(cat "result.txt")

# Publish the results via MQTT
mosquitto_pub -h "$MQTT_BROKER" -p "$MQTT_PORT" -u "$MQTT_USER" -P "$MQTT_PASS" -t "$MQTT_TOPIC" -m "$results"
```

**Comment by Adam-yes** [comment]
Hello alexis-coulombe ,

Thank you so much for your comprehensive response!!!

I have the following situation: I have two separate Python scripts - one for sending images and another one for receiving them. When I run the sending script on a separate computer, I'm able to receive and display the images on my laptop.

##########################################
script to send:

import paho.mqtt.client as mqtt
import cv2
import numpy as np

def on_connect(client, userdata, flags, rc):
    client.publish("mein/Topic", "Hallo")

client = mqtt.Client()
client.on_connect = on_connect
client.connect("XY",1900, 40)
client.loop_start()

dev = 0
cap = cv2.VideoCapture('/dev/video'+str(dev), cv2.CAP_V4L)

while(cap.isOpened()):
    ret,frame = cap.read()
    if ret ==True:
        rc, payload = cv2.imencode('.png',frame)
        if not rc:
            print('could not encode image')
            continue
        client.publish("mein/Topic", payload.tobytes())


##########################################

script to receive:

import cv2
import numpy as np
import paho.mqtt.client as mqtt

def on_connect(client, userdata, flags, rc):
    print(f"Connected with result code {str(rc)}")
    client.subscribe("mein/Topic")

def on_message(client, userdata, msg):
    print(f"Received message from topic: {msg.topic}")
    nparr = np.frombuffer(msg.payload, np.uint8)
    frame = cv2.imdecode(nparr, cv2.IMREAD_COLOR)
    cv2.imshow('frame', frame)
    cv2.waitKey(1)

client = mqtt.Client()
client.on_connect = on_connect
client.on_message = on_message

client.connect("XY", 1900, 40)
client.loop_forever()
##########################################


I would like to have a clearer understanding on how I can incorporate the sending script so that it can be used with your plugin and have the images sent continuously. Is it possible to simply save the entire sending script as a bash script, make it executable, and run it through your plugin using the script's name?

In regards to the packages, should I install them through your bash or should I incorporate them within the sending script itself? Could be there a problem?

Thank you so much!!

Cheers!

**Comment by alexis-coulombe** [comment]
If I understand correctly you have the receive script on another computer and the send script on the pi.

You want to send an image (probably taken from a webcam) to your receive script continuously, say once an hour for an example. You can run your sending script manually through my plugin, but if you want it to also run hourly you need to create a cronjob.

To manually run your sending script with my plugin, you can save this command in my plugin setting page: 
```
python3 /path/to/your/sending-script.py
```

**(if python3 does not work, try replacing it with /usr/bin/python3)**

To execute this command hourly, do the following in a terminal: 
```
crontab -e
```
Select your preferred editor (nano in my case).

```
0 * * * * /usr/bin/python3 /path/to/your/sending-script.py
```
And then press Ctrl + s to save and Ctrl + x to quit.

**Comment by alexis-coulombe** [comment]
Closed since no reply
