### ISSUE TITLE
Allow the addition of multiple buttons, each with its own command

### ISSUE THREAD

**Issue by GoTVm** [Chargnn/Octoprint-CmdExec#7]
I'd like to preface this by saying that your plugin is the only one that manages to run Python scripts in my use case.

I need to be able to add a number of buttons, each running their own script (for now two), but I can't seem to find a way to do so currently. The plugin would become much more useful if it could handle multiple buttons.

**Comment by alexis-coulombe** [comment]
As of right now my plugin does not allow for multiple buttons, but it may be a good idea! I'll need to check the most effective approach to integrate additional buttons/commands without overcrowding the top toolbar. But i definitely will add that soon!

**Comment by GoTVm** [comment]
Maybe a drop-down menu like the one with the power functions? Ive never really tried to add UI components, it might not even be possible.
________________________________

**Comment by FreunderNacht** [comment]
Several comandos with a drop-down menu were also interesting for me.

**Comment by fly74** [comment]
Buttons after each other would be fine, I have enough space :)
![image](https://github.com/user-attachments/assets/ddd8faf7-d92b-4b50-be14-6d149f275479)

**Comment by jdwhite** [comment]
How about making it configurable? Row of X buttons versus drop-down menu? Perhaps allowing for a combination where you could have some buttons that perform actions and some that are drop-downs?

**Comment by alexis-coulombe** [comment]
I'll try to find some time this week to implement this feature. Probably something with a dropdown

**Comment by fly74** [comment]
The row of buttons would be more my favorite. I use it for selecting different light modes to the enclosure. With drop down it would be not as comfortable as it could.

**Comment by alexis-coulombe** [comment]
I'll do both, how about that ;) You will have a choice between dropdown or not (everything on the toolbar)

**Comment by PaulsBits** [comment]
Dont forget to change the version number in setup.py. In octoprint it still shows 1.0.4 even though the 1.0.6 version is downloaded :)

**Comment by alexis-coulombe** [comment]
I have published a new version. It will be available when octoprint has updated its plugins references. Do not hesitate if you encounter problems to open another ticket.

I would have liked to be able to dynamically add commands without limits, but managing arrays in settings is very limiting. The way octoprint handles parameters, values/updates them (or I didn't quite understand how it works).

So I added a total of 4 fields to make sure you can add more than one command. This way also makes backwards compatibility easier.

This is not ideal, if anyone would like to contribute to finding a solution they are welcome. In the meantime I'll keep my eyes open if I find anything of my own.
