### ISSUE TITLE
New Version only show dropdown, even if list is selected and has no icon to click on

### ISSUE THREAD

**Issue by fly74** [Chargnn/Octoprint-CmdExec#9]
![image](https://github.com/user-attachments/assets/b21121b4-1250-43fc-900b-739f384151a1)

**Comment by alexis-coulombe** [comment]
The text seems to be the same color as your background. What plugin or browser extension do you have to get the dark theme ?

**Comment by fly74** [comment]
It's the UI Customizer plugin. Worked with your plugin in V1.0.4 perfect.

![image](https://github.com/user-attachments/assets/f3123250-a369-4cdc-ad41-1c25a7ef2d7a)

**Comment by alexis-coulombe** [comment]
I'll look into this, there will be a patch today

**Comment by fly74** [comment]
and this theme
![image](https://github.com/user-attachments/assets/3194db6b-2bb7-464f-aac0-642e81e2ad26)

**Comment by alexis-coulombe** [comment]
I'll publish a new version, here's the result: 
![Screenshot from 2024-09-14 09-32-26](https://github.com/user-attachments/assets/82e2c942-5bc1-4f0b-b60a-ca6df9e34ad4)
![Screenshot from 2024-09-14 09-34-47](https://github.com/user-attachments/assets/072a536e-a7f8-433b-89c6-60db11adcf2e)

I will work to make the dropdown look better in the near futur

**Comment by jdwhite** [comment]
@alexis-coulombe Thank you for your work on this. Looks great!

**Comment by fly74** [comment]
Works great, nice version number :)

**Comment by fly74** [comment]
@alexis-coulombe I would like to ask if you can extend the number of commands. I would need 7 commands in my case.
